class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'extract3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list3'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'lol'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.CountCommand = 'cnt'

BotCommands = _BotCommands()
