class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'extract4'
        self.TarMirrorCommand = 'tarmirror4'
        self.CancelMirror = 'cancel4'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list4'
        self.StatusCommand = 'status4'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart4'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'lol'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.CountCommand = 'cnt'

BotCommands = _BotCommands()
