class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mr'
        self.UnzipMirrorCommand = 'ex1'
        self.TarMirrorCommand = 'tarmi1'
        self.CancelMirror = 'can'
        self.CancelAllCommand = 'cancelal'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart8'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.WatchCommand = 'wat'
        self.TarWatchCommand = 'tarw'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.CountCommand = 'count'

BotCommands = _BotCommands()
